apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::294973688166:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-66M19GPP8GNH
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::294973688166:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-01T18:00:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1497"
  uid: 900beb96-5d03-4fa5-9273-883d205754dc
